### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [bmihaila/dustmod#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by bmihaila** [comment]
Hi unixorn

That request was fast! Did not have time to produce a screenshot till now but got to it.
See the Readme which includes a screenshot, or use this direct link https://github.com/bmihaila/dustmod/blob/master/screenshots/Screenshot_all_1.png

**Comment by unixorn** [comment]
I check GH every few days for new ZSH plugins and themes to add to the list :-)

**Comment by bmihaila** [comment]
👍 
Now I'll have to go through all the stuff in your list - again.
